[tool.black]
line-length = 79
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.venv
  | \env
  | migrations
)/
'''
[tool.isort]
profile = "black"
line_length = 79
multi_line_output = 3
include_trailing_comma = true
